// <auto-generated />
using System;
using Comet.DataAccess.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comet.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251229110946_tretasreka")]
    partial class tretasreka
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Comet.Domain.Entities.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BidTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("BuyerUserId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsWinningBid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyerUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("Comet.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AuctionStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BuyerUserId")
                        .HasColumnType("int");

                    b.Property<string>("ColorBottomSide")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ColorTopSide")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Defects")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("GrossWeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int?>("LibertyUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("MinimumBidPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetWeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Thickness")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<string>("ZincCoating")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerUserId");

                    b.HasIndex("LibertyUserId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuctionStartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ColorTopSide = "RAL 9002 LTP",
                            CreatedAt = new DateTime(2025, 12, 29, 11, 9, 45, 440, DateTimeKind.Utc).AddTicks(1778),
                            Defects = "unpainted spots",
                            Grade = "DX51D +Z",
                            GrossWeight = 1465m,
                            IsPublished = false,
                            MinimumBidPrice = 0m,
                            NetWeight = 1465m,
                            ProductCategory = "FourthChoice",
                            ProductCode = "2501998/11",
                            ProductType = "PPG_Coil",
                            Thickness = 0.75m,
                            Width = 1500,
                            ZincCoating = "Z 140"
                        },
                        new
                        {
                            Id = 2,
                            AuctionStartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ColorBottomSide = "LZS 7030",
                            ColorTopSide = "RAL 9006",
                            CreatedAt = new DateTime(2025, 12, 29, 11, 9, 45, 440, DateTimeKind.Utc).AddTicks(1790),
                            Defects = "unpainted spots",
                            Grade = "S250GD +Z",
                            GrossWeight = 0.890m,
                            IsPublished = false,
                            MinimumBidPrice = 0m,
                            NetWeight = 0.880m,
                            ProductCategory = "FourthChoice",
                            ProductCode = "2503658/41",
                            ProductType = "PPG_Coil",
                            Thickness = 0.50m,
                            Width = 1250,
                            ZincCoating = "Z 140"
                        });
                });

            modelBuilder.Entity("Comet.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Report"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("Comet.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Comet.Domain.Entities.BuyerUser", b =>
                {
                    b.HasBaseType("Comet.Domain.Entities.User");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasIndex("CompanyName");

                    b.ToTable("BuyerUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 12, 29, 11, 9, 45, 440, DateTimeKind.Utc).AddTicks(1932),
                            Email = "customer1@buyer.com",
                            Password = "AQAAAAIAAYagAAAAEN5FiNedAWty+f2XEZ/urSVat2TzTklLWJUxEp5YBxMHSkizHvqk5hQ1PxESb/SIJw==",
                            RoleId = 3,
                            CompanyName = "SteelWorks Inc"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 12, 29, 11, 9, 45, 440, DateTimeKind.Utc).AddTicks(1939),
                            Email = "customer2@buyer.com",
                            Password = "AQAAAAIAAYagAAAAEN5FiNedAWty+f2XEZ/urSVat2TzTklLWJUxEp5YBxMHSkizHvqk5hQ1PxESb/SIJw==",
                            RoleId = 3,
                            CompanyName = "MetalPro Industries"
                        });
                });

            modelBuilder.Entity("Comet.Domain.Entities.LibertyUser", b =>
                {
                    b.HasBaseType("Comet.Domain.Entities.User");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasIndex("FullName");

                    b.ToTable("LibertyUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 12, 29, 11, 9, 45, 440, DateTimeKind.Utc).AddTicks(1846),
                            Email = "admin@liberty.com",
                            Password = "AQAAAAIAAYagAAAAEFPMtFeiolPvXsWN1g9fjrBV1hwQI65nOjnL/Z7QZtMbJ1NUjOWKrpg6JBC+oY5Kkg==",
                            RoleId = 1,
                            FullName = "Liberty Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 12, 29, 11, 9, 45, 440, DateTimeKind.Utc).AddTicks(1852),
                            Email = "reports@liberty.com",
                            Password = "AQAAAAIAAYagAAAAEI30L+x9SLK376ddrhdlCZSzVoF2i/7/jOmCcDIiLRoh+yVKQsrGaG0VlmJvgJR5+Q==",
                            RoleId = 2,
                            FullName = "Report User"
                        });
                });

            modelBuilder.Entity("Comet.Domain.Entities.Bid", b =>
                {
                    b.HasOne("Comet.Domain.Entities.BuyerUser", "BuyerUser")
                        .WithMany("Bids")
                        .HasForeignKey("BuyerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Comet.Domain.Entities.Product", "Product")
                        .WithMany("Bids")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyerUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Comet.Domain.Entities.Product", b =>
                {
                    b.HasOne("Comet.Domain.Entities.BuyerUser", "BuyerUser")
                        .WithMany("Products")
                        .HasForeignKey("BuyerUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Comet.Domain.Entities.LibertyUser", "LibertyUser")
                        .WithMany("Products")
                        .HasForeignKey("LibertyUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("BuyerUser");

                    b.Navigation("LibertyUser");
                });

            modelBuilder.Entity("Comet.Domain.Entities.User", b =>
                {
                    b.HasOne("Comet.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Comet.Domain.Entities.BuyerUser", b =>
                {
                    b.HasOne("Comet.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Comet.Domain.Entities.BuyerUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Comet.Domain.Entities.LibertyUser", b =>
                {
                    b.HasOne("Comet.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Comet.Domain.Entities.LibertyUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Comet.Domain.Entities.Product", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("Comet.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Comet.Domain.Entities.BuyerUser", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Comet.Domain.Entities.LibertyUser", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
